title: Pavlo Mysak
Description: 'email: pavlomysak@gmail.com'
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
